In [1]:
print("hello")

hello


In [2]:
import torch

In [11]:
original = torch.load("lookback-ratio-original.pt")

In [12]:
len(original)

2

In [13]:
original[0].keys()

dict_keys(['data_index', 'model_completion', 'model_completion_ids', 'full_input_text', 'lookback_ratio'])

In [14]:
original[0]["lookback_ratio"][0][0]

tensor([0.0728, 0.5034, 0.4207, 0.3586, 0.5151, 0.3909, 0.2485, 0.2781, 0.3701,
        0.4524, 0.3481, 0.4834, 0.4248, 0.2725, 0.2438, 0.3423, 0.4500, 0.2810,
        0.2487, 0.3809, 0.1884, 0.2031, 0.4116, 0.3032, 0.4583, 0.4885, 0.4277,
        0.4810, 0.4604, 0.3137, 0.4250, 0.4204, 0.4836, 0.2224, 0.1805, 0.1532,
        0.2422, 0.4563, 0.2357])

In [35]:
fixed = torch.load("lookback-ratio-fixed.pt")

In [36]:
fixed[0]["lookback_ratio"][0][0]

tensor([1.0000, 0.2249, 0.2996, 0.4004, 0.4331, 0.2642, 0.2356, 0.2371, 0.3269,
        0.3633, 0.3896, 0.4370, 0.3867, 0.2742, 0.2388, 0.3044, 0.3967, 0.2900,
        0.2529, 0.3374, 0.3064, 0.1873, 0.3916, 0.2932, 0.4277, 0.4634, 0.4050,
        0.4358, 0.4216, 0.2983, 0.3904, 0.3948, 0.4465, 0.2788, 0.1948, 0.1619,
        0.2444, 0.4319, 0.2424])

In [37]:
simplified = torch.load("lookback-ratio-simplified.pt")

In [38]:
simplified[0]["lookback_ratio"][0][0]

tensor([1.0000, 0.2249, 0.2996, 0.4004, 0.4331, 0.2642, 0.2356, 0.2371, 0.3269,
        0.3633, 0.3896, 0.4370, 0.3867, 0.2742, 0.2388, 0.3044, 0.3967, 0.2900,
        0.2529, 0.3374, 0.3064, 0.1873, 0.3916, 0.2932, 0.4277, 0.4634, 0.4050,
        0.4358, 0.4216, 0.2983, 0.3904, 0.3948])